CREATE TABLE IF NOT EXISTS users (  
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--  CREATE DATABASE IF NOT EXISTS db_mvc;
-- GRANT ALL PRIVILEGES ON db_mvc.* TO 'dev_user'@'localhost';
-- FLUSH PRIVILEGES;
